server:
  license-path: .
  default-voice-port: 9987
  voice-ip:
    - 0.0.0.0
    - "::"
  machine-id: ""
  threads-voice-udp: 5
  log-path: logs
  log-append: 1
  filetransfer-port: 30033
  filetransfer-ip:
    - 0.0.0.0
    - "::"
  accept-license: accept

  database:
    plugin: sqlite3
    sql-path: sql/
    sql-create-path: create_sqlite/
    client-keep-days: 30
    config:
      skip-integrity-check: 0

  query:
    pool-size: 2
    log-timing: 3600
    ip-allow-list: query_ip_allowlist.txt
    ip-block-list: query_ip_denylist.txt
    admin-password: ""
    log-commands: 1
    skip-brute-force-check: 0
    buffer-mb: 20
    documentation-path: serverquerydocs
    timeout: 300

    ssh:
      enable: 0
      port: 10022
      ip:
        - 0.0.0.0
        - "::"
      rsa-key: ssh_host_rsa_key

    http:
      enable: 1
      port: 10080
      ip:
        - 0.0.0.0
        - "::"